print("Salut")
print("Hello, World!")
print("ceva")
print("buna")
print('acum')
print("Lavi")
print("Adela")
print('acum')
print("salut sunt cristi")
print(27**8)
print("Adela")
print("hello")
print('lorena')